/* 武器派生树数据
 * moves 元组：[id, 名称, 父招id|null, 输入串, 类型, 条件, 备注, 标记]
 * 输入串：'>' 分隔依次按键；'+' 同时按键；结尾 '!' 表示长按
 * 类型：start 起手 / combo 派生 / special 特殊 / state 状态与资源 / air 空中 / mount 骑乘 / focus 集中
 * 标记：'w' 仅荒野 / 'o' 仅世界
 * 全部招式为资料整理，未在游戏内逐招核对
 */
window.WEAPON_TREES = {
gs: { name:'大剑', en:'Great Sword', cls:'melee',
  gauge:{ name:'蓄力阶段', desc:'长按攻击键进入蓄力，三段松开，威力与硬直递增', keys:['c'] },
  tips:['蓄力键：荒野=R／世界冰原=鼠标侧键2(MB5)。长按最频繁，建议放在顺手键位。','主打头部，可积累眩晕值；蓄力中用走位修正站位。'],
  moves:[
    ['draw','拔刀斩',null,'t','start','纳刀时',''],
    ['tate','纵斩','draw','t','combo','',''],
    ['yoko','横斩','tate','t','combo','',''],
    ['age','上捞斩','yoko','tc','combo','',''],
    ['charge','蓄力斩',null,'c!','special','任意攻击后长按','分三段蓄力'],
    ['charge2','强蓄力斩','charge','c!','special','继续长按',''],
    ['charge3','真·蓄力斩','charge2','c!','special','继续长按','最高威力'],
    ['tackle','肩撞','charge','x','combo','蓄力中','取消蓄力并突进'],
    ['tackle_charge','肩撞接蓄力','tackle','c!','combo','','可重新进入蓄力'],
    ['jump','跳跃纵斩',null,'t','air','空中',''],
    ['jump_yoko','空中横斩','jump','t','air','',''],
    ['mount','骑乘攻击','jump_yoko','t','mount','命中可积累骑乘值',''],
    ['focus','集中弱点攻击',null,'l2>r1','focus','集中模式中','先长按 L2 进入集中模式，再按 R1','w']
  ]},
ls: { name:'太刀', en:'Long Sword', cls:'melee',
  gauge:{ name:'练气槽 / 刃色', desc:'攻击积攒练气槽，气刃斩消耗；气刃大回旋命中后开刃（白→黄→红）', keys:['r2'] },
  tips:['气刃斩：荒野=R／世界冰原=鼠标侧键2(MB5)。','见切斩需要在怪物攻击瞬间使用，成功后回复练气槽。'],
  moves:[
    ['draw','拔刀斩',null,'t','start','纳刀时',''],
    ['tate','纵斩','draw','t','combo','',''],
    ['tsuki','突刺','tate','c','combo','',''],
    ['kiriage','上斩','tsuki','t','combo','',''],
    ['renki1','气刃斩·一',null,'r2','special','练气槽一段以上',''],
    ['renki2','气刃斩·二','renki1','r2','special','',''],
    ['renki3','气刃斩·三','renki2','r2','special','',''],
    ['daikaiten','气刃大回旋','renki3','r2','special','气刃斩连段末尾','命中后开刃'],
    ['mikiri','见切斩',null,'r2+c','special','怪物攻击瞬间','成功后回复练气槽并位移'],
    ['special_draw','特殊纳刀',null,'r2+x','special','攻击后','进入居合架势'],
    ['iai','居合拔刀斩','special_draw','t','combo','特殊纳刀后',''],
    ['iai_renki','居合气刃斩','special_draw','r2','combo','特殊纳刀后',''],
    ['hikou','飞翔蹴り',null,'x','special','荒野新增','输入待核对','w'],
    ['focus','集中弱点攻击',null,'l2>r1','focus','集中模式中','','w']
  ]},
sns: { name:'片手剑', en:'Sword & Shield', cls:'melee',
  gauge:{ name:'无特殊资源', desc:'攻守一体，持刀状态可直接使用道具', keys:['r2'] },
  tips:['持刀状态可直接使用道具与磨刀，不必收刀。','防御：荒野=R／世界冰原=鼠标侧键2(MB5)。'],
  moves:[
    ['draw','拔刀斩',null,'t','start','纳刀时',''],
    ['tate','纵斩','draw','t','combo','',''],
    ['jun','盾连斩','tate','t','combo','',''],
    ['suijun','水平斩','draw','c','combo','',''],
    ['kaeri','回斩','suijun','c','combo','',''],
    ['kaiten','回旋斩','kaeri','c','combo','',''],
    ['shin_kaiten','真回旋斩','kaiten','tc','combo','可 360° 调整方位',''],
    ['shield_bash','盾击','kaiten','c','combo','',''],
    ['backhop','后撤步',null,'ls+c!','special','方向后+长按',''],
    ['charge_slash','蓄力斩','backhop','c','combo','后撤步长按后',''],
    ['jump_slash','上撩跳斩','charge_slash','t','combo','蓄力斩命中后自动派生',''],
    ['kari','旋刈',null,'c','special','荒野新增','输入待核对','w'],
    ['guard','防御',null,'r2','state','长按',''],
    ['use_item','持刀使用道具',null,'r2+s','special','持刀时',''],
    ['air','跳跃攻击',null,'t','air','空中',''],
    ['focus','集中弱点攻击',null,'l2>r1','focus','集中模式中','','w']
  ]},
db: { name:'双剑', en:'Dual Blades', cls:'melee',
  gauge:{ name:'鬼人槽 / 耐力', desc:'鬼人化持续消耗耐力换取攻速与连段；荒野新增鬼人强化状态', keys:['r2'] },
  tips:['鬼人化：荒野=R／世界冰原=鼠标侧键2(MB5)。','耐力见底会自动解除鬼人化，注意节奏。'],
  moves:[
    ['kijin','鬼人化',null,'r2','state','消耗耐力','可随时切换'],
    ['kijin_off','解除鬼人化','kijin','r2','state','',''],
    ['renzan','乱舞',null,'t','start','',''],
    ['totsushin','突进斩',null,'c','start','',''],
    ['kaiten','回旋斩','totsushin','c','combo','',''],
    ['kijin_renzan','鬼人连斩','kijin','t','combo','鬼人化中',''],
    ['kijin_totsushin','鬼人突进斩','kijin','c','combo','鬼人化中',''],
    ['kijin_ranbu','鬼人乱舞',null,'tc','special','鬼人化中',''],
    ['suberu','滑步斩',null,'x','combo','回避中派生',''],
    ['air_ranbu','空中回旋乱舞',null,'t','air','空中',''],
    ['mount','骑乘攻击','air_ranbu','t','mount','命中可积累骑乘值',''],
    ['focus','集中弱点攻击',null,'l2>r1','focus','集中模式中','','w']
  ]},
hm: { name:'大锤', en:'Hammer', cls:'melee',
  gauge:{ name:'蓄力阶段', desc:'长按蓄力三段，主打头部积累眩晕', keys:['r2'] },
  tips:['蓄力：荒野=R／世界冰原=鼠标侧键2(MB5)。','蓄力中可用回避取消，调整站位再释放。'],
  moves:[
    ['tate','纵挥',null,'t','start','',''],
    ['uchi','敲打（三连）','tate','c','combo','',''],
    ['gochida','五连敲','uchi','t','combo','敲打派生',''],
    ['charge','蓄力一段',null,'r2!','special','长按',''],
    ['charge2','蓄力二段','charge','r2!','special','继续长按',''],
    ['charge3','蓄力三段','charge2','r2!','special','继续长按',''],
    ['kaiten','旋转攻击','charge3','t','combo','三段蓄力释放后',''],
    ['hon','本垒打','kaiten','tc','combo','连招收尾','高威力'],
    ['kyo_strong','强蓄力','charge','r2+c','special','蓄力中',''],
    ['ageage','上捞挥','kaiten','c','combo','',''],
    ['air','空中纵挥',null,'t','air','空中',''],
    ['mount','骑乘攻击','air','t','mount','',''],
    ['focus','集中弱点攻击',null,'l2>r1','focus','集中模式中','','w']
  ]},
hh: { name:'狩猎笛', en:'Hunting Horn', cls:'melee',
  gauge:{ name:'旋律 / 音色', desc:'攻击积攒音色，演奏发动增益；荒野新增响玉与共鸣', keys:['r2'] },
  tips:['演奏：荒野=R／世界冰原=鼠标侧键2(MB5)。','建议为演奏设置第二键位（如鼠标中键），方便方向+演奏。'],
  moves:[
    ['atk1','攻击·音色一',null,'t','start','',''],
    ['atk2','攻击·音色二',null,'c','start','',''],
    ['atk3','攻击·音色三',null,'tc','start','',''],
    ['ensou','演奏',null,'r2','special','积攒旋律后',''],
    ['ensou_dir','方向演奏','ensou','ls+r2','special','配合左摇杆方向','带位移'],
    ['sanyon','三音演奏',null,'tc','special','三色音色齐备',''],
    ['melody','旋律发动','ensou','r2','special','旋律达成',''],
    ['kyomei','共鸣',null,'r2','special','荒野','输入待核对','w'],
    ['houdama','响玉设置',null,'tc','special','荒野','输入待核对','w'],
    ['air','空中攻击',null,'t','air','空中',''],
    ['mount','骑乘攻击','air','t','mount','',''],
    ['focus','集中弱点攻击',null,'l2>r1','focus','集中模式中','','w']
  ]},
ln: { name:'长枪', en:'Lance', cls:'melee',
  gauge:{ name:'盾牌 / 反击窗口', desc:'以防御为核心，抓准时机反击', keys:['r2'] },
  tips:['防御：荒野=R／世界冰原=鼠标侧键2(MB5)。常按建议设第二键位。','力量防御可抵御大威力攻击。'],
  moves:[
    ['toshi1','中段突刺',null,'t','start','',''],
    ['toshi2','上段突刺','toshi1','t','combo','',''],
    ['toshi3','下段突刺','toshi2','t','combo','',''],
    ['guard','防御',null,'r2','state','长按',''],
    ['hangeki','防御反击刺','guard','r2+c','special','防御中派生','抓准时机'],
    ['chikara','力量防御','guard','r2+x','state','防御中派生',''],
    ['shield_bash','盾击','chikara','c','combo','力量防御中',''],
    ['jump_toshi','跳跃突刺','guard','r2+t','special','防御中派生',''],
    ['dash','冲刺攻击',null,'ls+r2','special','收刀+方向',''],
    ['air','空中突刺',null,'t','air','空中',''],
    ['mount','骑乘攻击','air','t','mount','',''],
    ['focus','集中弱点攻击',null,'l2>r1','focus','集中模式中','','w']
  ]},
gl: { name:'铳枪', en:'Gunlance', cls:'melee',
  gauge:{ name:'弹药 / 龙击炮冷却', desc:'炮击消耗弹药，快速装填回复；龙击炮威力大但冷却长', keys:['c','r2'] },
  tips:['防御刺=R+左键（荒野），可三连。','快填=R+右键（荒野）／MB5+右键（世界冰原）。'],
  moves:[
    ['toshi','刺击',null,'t','start','',''],
    ['bougyo_toshi','防御刺','toshi','r2+t','combo','R2+△','可三连'],
    ['ageage','上捞斩',null,'tc','start','',''],
    ['hougeki','炮击',null,'c','special','消耗弹药',''],
    ['chikara_hou','蓄力炮','hougeki','c!','special','长按',''],
    ['zen_dan','全弹发射','hougeki','tc','special','炮击后派生','消耗全部弹药'],
    ['ryu_geki','龙击炮',null,'r2+t+c','special','','威力大、冷却长'],
    ['kai_ten','快速装填',null,'r2+c','state','','回复弹药'],
    ['guard','防御',null,'r2','state','长按',''],
    ['air','空中刺击',null,'t','air','空中',''],
    ['mount','骑乘攻击','air','t','mount','',''],
    ['focus','集中弱点攻击',null,'l2>r1','focus','集中模式中','','w']
  ]},
sa: { name:'斩击斧', en:'Switch Axe', cls:'melee',
  gauge:{ name:'剑槽 / 瓶', desc:'剑模式积攒槽位并装填瓶，斧模式消耗瓶爆发', keys:['r2','tc'] },
  tips:['变形：荒野=R／世界冰原=鼠标侧键2(MB5)。','属性解放突刺为△+○长按。'],
  moves:[
    ['fu_tate','斧·纵斩',null,'t','start','斧模式',''],
    ['fu_yoko','斧·横斩','fu_tate','c','combo','',''],
    ['ken_tate','剑·纵斩',null,'t','start','剑模式',''],
    ['ken_yoko','剑·横斩','ken_tate','c','combo','',''],
    ['henkei','变形斩',null,'r2','special','剑⇄斧切换',''],
    ['kaihou','属性解放突刺','ken_tate','tc!','special','剑模式长按',''],
    ['shuuryou','属性解放终结','kaihou','tc','special','解放突刺后','高出力'],
    ['souchou','瓶装填',null,'r2+c','state','剑槽积攒后',''],
    ['souka','属性强化','souchou','r2+c','state','装填后',''],
    ['air','空中攻击',null,'t','air','空中',''],
    ['mount','骑乘攻击','air','t','mount','',''],
    ['focus','集中弱点攻击',null,'l2>r1','focus','集中模式中','','w']
  ]},
cb: { name:'盾斧 / 充能斧', en:'Charge Blade', cls:'melee',
  gauge:{ name:'瓶', desc:'剑模式积攒能量装瓶，斧模式消耗瓶爆发', keys:['r2','tc'] },
  tips:['防御：荒野=R／世界冰原=鼠标侧键2(MB5)。需要长时间按住，改键优先级最高。','盾突=△+○（鼠标侧键1／MB4）。'],
  moves:[
    ['ken_tate','剑·纵斩',null,'t','start','剑模式',''],
    ['tate_totsu','盾突刺','ken_tate','tc','combo','','可三连'],
    ['ken_yoko','剑·回旋斩','tate_totsu','t','combo','',''],
    ['juuden','瓶装填',null,'r2+c','state','能量积攒后',''],
    ['kousoku','属性强化回填','juuden','r2+c','state','瓶充能后',''],
    ['henkei','变形为斧','kousoku','r2+t','state','',''],
    ['guard','防御',null,'r2','state','长按','抓准时机触发精准防御'],
    ['seikai','精准防御反击','guard','t','combo','精准防御后',''],
    ['fu_kaihou','斧·属性解放斩',null,'tc','special','斧模式','消耗瓶'],
    ['chou_kaihou','超高出力属性解放斩','fu_kaihou','tc','special','强化状态中','最高爆发'],
    ['denki','电锯模式',null,'r2!','special','荒野','输入待核对','w'],
    ['air','空中攻击',null,'t','air','空中',''],
    ['mount','骑乘攻击','air','t','mount','',''],
    ['focus','集中弱点攻击',null,'l2>r1','focus','集中模式中','','w']
  ]},
ig: { name:'操虫棍', en:'Insect Glaive', cls:'melee',
  gauge:{ name:'精华（三灯）', desc:'猎虫采集怪物精华点亮三灯：红攻击、白移动、橙防御', keys:['l2','t'] },
  tips:['猎虫瞄准：荒野=Alt／鼠标侧键2；世界冰原=C长按／鼠标中键。','世界首发版 L2=V 较难按，建议与 E 对调。'],
  moves:[
    ['rengeki','连击',null,'t','start','',''],
    ['yoko','横斩','rengeki','c','combo','',''],
    ['mushi_aim','猎虫瞄准',null,'l2!','special','长按',''],
    ['mushi_shot','发射猎虫','mushi_aim','l2+t','special','瞄准中△','采集精华'],
    ['mushi_back','收回猎虫','mushi_shot','l2+c','special','瞄准中○',''],
    ['aka','红精华（攻击强化）','mushi_shot','l2+t','state','采集头部',''],
    ['shiro','白精华（移动强化）','mushi_shot','l2+t','state','采集翅膀',''],
    ['ora','橙精华（防御强化）','mushi_shot','l2+t','state','采集躯体',''],
    ['bou','撑杆跳',null,'r2+x','special','R2+✕',''],
    ['air','空中攻击','bou','t','air','空中',''],
    ['kyushuu','急袭斩',null,'t','special','三灯状态',''],
    ['hishou','飞天螺旋斩','kyushuu','l2+c','special','急袭斩后','清空精华；仅荒野','w'],
    ['mount','骑乘攻击','air','t','mount','',''],
    ['focus','集中弱点攻击',null,'l2>r1','focus','集中模式中','','w']
  ]},
lbg: { name:'轻弩', en:'Light Bowgun', cls:'ranged',
  gauge:{ name:'弹药 / 弹种', desc:'不同弹种威力与效果不同，装填与走位是核心', keys:['t','l2'] },
  tips:['射击=鼠标左键；装填=荒野R／世界冰原MB4。','瞄准=Alt／侧键2（荒野）；长按鼠标右键（世界冰原）。'],
  moves:[
    ['shageki','射击',null,'r2','start','',''],
    ['aim','瞄准',null,'l2!','special','长按',''],
    ['souten','装填',null,'t','state','',''],
    ['tane_up','切换弹种（上）',null,'d_up','state','方向键上',''],
    ['tane_down','切换弹种（下）',null,'d_down','state','方向键下',''],
    ['suberu','滑步回避',null,'x','combo','回避位移',''],
    ['kibaku','起爆龙弹',null,'c','special','世界','输入待核对','o'],
    ['special_shot','特殊弹',null,'c','special','荒野','输入待核对','w'],
    ['melee','近战敲击',null,'c','special','贴身时',''],
    ['focus','集中弱点攻击',null,'l2>r1','focus','集中模式中','','w']
  ]},
hbg: { name:'重弩', en:'Heavy Bowgun', cls:'ranged',
  gauge:{ name:'弹药 / 机关', desc:'威力高但机动差，特殊弹与机关有准备动作', keys:['t','l2'] },
  tips:['射击=鼠标左键；装填=荒野R／世界冰原MB4。','蹲射威力高但无法移动，注意时机。'],
  moves:[
    ['shageki','射击',null,'r2','start','',''],
    ['aim','瞄准',null,'l2!','special','长按',''],
    ['souten','装填',null,'t','state','',''],
    ['tane_up','切换弹种（上）',null,'d_up','state','方向键上',''],
    ['tane_down','切换弹种（下）',null,'d_down','state','方向键下',''],
    ['kikan','机关龙弹',null,'c','special','特殊装备动作',''],
    ['zashiki','蹲射',null,'c!','special','长按','威力高但无法移动'],
    ['guard','盾牌防御',null,'r2','state','装配盾牌零件时',''],
    ['suberu','滑步回避',null,'x','combo','回避位移',''],
    ['melee','近战敲击',null,'c','special','贴身时',''],
    ['focus','集中弱点攻击',null,'l2>r1','focus','集中模式中','','w']
  ]},
bw: { name:'弓', en:'Bow', cls:'ranged',
  gauge:{ name:'蓄力等级 / 瓶', desc:'长按蓄力决定箭矢威力；瓶强化效果', keys:['r2','t'] },
  tips:['射击·蓄力=左键长按；上瓶=荒野R／世界冰原MB4。','滑步可保持蓄力等级。'],
  moves:[
    ['shageki','通常射击',null,'r2','start','',''],
    ['chikara1','蓄力一段','shageki','r2!','special','长按',''],
    ['chikara2','蓄力二段','chikara1','r2!','special','继续长按',''],
    ['chikara3','蓄力三段','chikara2','r2!','special','继续长按',''],
    ['aim','瞄准',null,'l2!','special','长按',''],
    ['gangsha','刚射',null,'c','special','蓄力中',''],
    ['kyokusha','曲射','gangsha','c!','special','长按','范围效果'],
    ['suberu','滑步',null,'x','combo','回避并保持蓄力',''],
    ['bin','装填 / 卸瓶',null,'t','state','',''],
    ['ryu_no_ya','龙之矢','aim','r2+c','special','瞄准中','贯穿伤害'],
    ['mount','骑乘攻击','suberu','t','mount','',''],
    ['focus','集中弱点攻击',null,'l2>r1','focus','集中模式中','','w']
  ]}
};
